# Generated by Django 5.1.4 on 2026-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('role', models.CharField(blank=True, default='', max_length=256)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('opencode', 'OpenCode')], default='deepseek', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('memory_enabled', models.BooleanField(default=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_iterations', models.IntegerField(default=10)),
                ('schedule_config', models.JSONField(blank=True, null=True)),
                ('interaction_rules', models.JSONField(blank=True, default=dict)),
                ('allowed_agents', models.JSONField(blank=True, default=list)),
                ('enabled_channels', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
