# Generated by Django 5.1.4 on 2026-05-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('opencode', 'OpenCode'), ('grok', 'Grok'), ('gemini', 'Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='deepseek', max_length=32),
        ),
    ]
