# Generated by Django 5.1.4 on 2026-06-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
